### ISSUE TITLE
Readme file incomplete

### ISSUE THREAD

**Issue by FoxCode-Tesmia** [vivekkushalch/Indian-Sign-Language-Recognition-System#10]
can you please provide the details that how to run these files.

**Comment by Jeet-programmer** [comment]
Thank You very much for showing interest in our repo !!!
For the time being, we are working to fix the known bugs your one is also been added to the list 
Very soon we are gonna release a stable update resolving almost "all" the errors until then please stay tuned.
For now, you can try our hosted beta version in the replit:- https://replit.com/@key2innovation/Sanket-Beta
You can also download the files and run them on Localhost

Steps:-
1. Download the code from the link:- https://replit.com/@key2innovation/Sanket-Beta.
2. Click on the index.html it will open the browser.
3. Click on the translate page.
4. Then click on the camera button and wait a few seconds to let the model load(make sure to allow the camera permission).
5. This beta version is capable to detect the [I love you, Hello, Thank you, Welcome] (*expect spamming) in ISL(Indian Sign Language)
6. For making your version you can change the Google teachable machine links in the `modelURL` and `metadataURL` in  `/translate/app.js`  file models but remember to give us feedback for more improvements.

**Comment by FoxCode-Tesmia** [comment]
thankyou for your reply but i am not able to download these files can you help me how to download these files from the given link?

**Comment by vivekkushalch** [comment]
Yeha sure! Pls follow these steps and you will be able to download the zip of the entire project.
If you still face any problem pls let us know we will try our best to resolve it as soon as possible.

### **Steps:**

### **1. Goto Replit hosted link: https://replit.com/@key2innovation/Sanket-Beta**
### **2. Click on `Fork` button to Fork the repl** 
![FORK](https://raw.githubusercontent.com/vivekkushalch/Indian-Sign-Language-Recognition-System/testing/README-ASSETS/fork%20the%20repl.jpg)
![Re name Fork](https://github.com/vivekkushalch/Indian-Sign-Language-Recognition-System/blob/testing/README-ASSETS/fork%20repl%20confirm.jpg?raw=true)

### **3. Click on the three dots in the right near the file manager and select `Download as Zip` option**
![Download as zip](https://github.com/vivekkushalch/Indian-Sign-Language-Recognition-System/blob/testing/README-ASSETS/download%20zip.png?raw=true)

**Comment by FoxCode-Tesmia** [comment]
thank you now i downloaded the file but still a problem occur when i dont the index.html file it show only the structure of file no styles and working?
can you help me with this that how can i open the app correctly as i donot open correctly.

**Comment by vivekkushalch** [comment]
Due to the current URL structure of Sanket it requires a static server to serve its assets (img, styles...) 
To solve this you can use 
1. Use `Live Server` extension in `Vs Code` to run Sanket. This article will lead you the way > https://www.geeksforgeeks.org/how-to-enable-live-server-on-visual-studio-code/
**--- OR ---**
2. Start a `Python HTTP Server` in the root dir of Sanket where `index.html` is present using this command 
`python -m http.server` your app should be running at [http://localhost:8000](http://localhost:8000)
**--- OR ---**
3. Start a `Node HTTP Server`  in the root dir of Sanket where `index.html` is present using this command   
`npx http-server` it should display the list of urls on which your app is running by default you can visit [http://localhost:8080](http://localhost:8080)

If still face any problem please let us know, we are happy to help!
